### ISSUE TITLE
如何设置字体？

### ISSUE THREAD

**Issue by narukamiko** [kooritea/electronic-wechat#90]
Archlinux，默认的字体看上去很模糊，如何设置字体？

**Comment by kooritea** [comment]
在设置里面启用自定义css
```css
body{
     font-size:20px!important;
}
```

根据自己需要改就好了
